feat: add options validation
nearform/graphql-auto-federate pull request #10
Opened 2022-05-10 13:40 UTC by ianlnf

- Adds options validation
- Updates readme

resolves #9

2022-05-13 12:15 UTC, simone-sanfratello commented on lib/federate.js
> +  const defaultOptions = { auto: true }
`defaultOptions` can be defined outside of the function

2022-05-13 12:16 UTC, simone-sanfratello commented on lib/federate.js
> +  if (!url) {
I'd move this in a validation function too, and check also for type string

2022-05-13 15:37 UTC, mcollina approved these changes
lgtm

2022-05-25 04:16 UTC, simone-sanfratello requested changes

2022-05-25 04:16 UTC, simone-sanfratello commented on lib/validators.js
> +function validateUrl(url) {
validate the url with `URL` class

2022-05-25 04:16 UTC, simone-sanfratello commented on package.json
> +    "test:watch": "tap test/*.test.js -w",
please remove this

2022-05-25 04:16 UTC, simone-sanfratello commented on lib/validators.js
> +  if (resolverObject.__resolveReference == null) {
`__resolveReference` is not mandatory

2022-05-25 04:16 UTC, simone-sanfratello commented on test/options.test.js
> +    expected: `options resolvers 'User' value must have a reference resolver`
add tests for the url, since there is a `validateUrl` function

2022-05-25 10:32 UTC, krisgrint commented on lib/validators.js
> +  if (resolverObject.__resolveReference == null) {
I have removed this check

2022-05-25 10:34 UTC, krisgrint commented on test/options.test.js
> -const { autoOptions } = require('../lib/options')
they have been moved to `test/auto-options.test.js`

2022-05-25 13:26 UTC, simone-sanfratello approved these changes

2022-05-25 13:32 UTC, merged